sonar.organization=mfozmen
sonar.projectKey=mfozmen_mopsos
sonar.projectName=Mopsos

sonar.sources=src
sonar.exclusions=src/**/*.test.ts

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts

# Written by `npm run test:coverage` in the CI job before the scan runs.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
